### ISSUE TITLE
Team feedback and features design

### ISSUE THREAD

**Issue by matteocargnelutti** [harvard-lil/perma-extension#15]

**Comment by shljessie** [comment]
<img width="992" alt="Screen Shot 2022-07-18 at 4 25 58 PM" src="https://user-images.githubusercontent.com/59305253/179611166-aa0cc22e-30f2-4a42-9cc1-b42731e63bda.png">

**Comment by shljessie** [comment]
<img width="957" alt="Screen Shot 2022-07-18 at 4 26 15 PM" src="https://user-images.githubusercontent.com/59305253/179611243-eb2af42d-35b2-4cd1-8f9e-6abd0e4d18a8.png">

**Comment by shljessie** [comment]
<img width="704" alt="Screen Shot 2022-07-18 at 4 27 21 PM" src="https://user-images.githubusercontent.com/59305253/179611432-ef7f732e-df56-4940-9a75-3addf12fe9d7.png">

**Comment by shljessie** [comment]
<img width="611" alt="Screen Shot 2022-07-18 at 4 28 10 PM" src="https://user-images.githubusercontent.com/59305253/179611572-1251781d-bc78-47c0-b40d-32eebeb15295.png">

**Comment by matteocargnelutti** [comment]
@shljessie : Thank you very much for having a look!

---

### Re: Dropdown arrow

Good catch! Fixed 😄 .

<img width="355" alt="Screen Shot 2022-07-18 at 6 08 40 PM" src="https://user-images.githubusercontent.com/625889/179625742-a003be6e-df90-476b-bd49-8b931f475dbf.png">

---

### Re: "Ready" status message

This is the default status message that shows a few seconds after any action is completed (or errored out!).
I agree that it's a bit unclear, and I am not sure what to put there. Suggestions welcome 😄 .

---

### Re: Archive IDs 

<img width="231" alt="Screen Shot 2022-07-18 at 6 13 48 PM" src="https://user-images.githubusercontent.com/625889/179626213-e432fe72-51ab-4cce-b852-434fdd3763ce.png">

I am not certain I 100% understand your question. 
Do you mean: how do IDs get assigned and why are they in this format? 

---

### Re: More precise status messages when switching between private and public mode 

Agreed, this needs to be more precise.
I think this works a bit better? 

https://user-images.githubusercontent.com/625889/179628470-e10d2445-27a9-41e0-84a2-758a5439e413.mov

---

### Re: Changing color of privacy toggle buttons based on current status

That's a good idea, I think 👍 . Implemented the following. 

https://user-images.githubusercontent.com/625889/179629294-dd644b6c-bd43-404a-81e6-f599f708e1e4.mov

---

### Re: Relation between the user's file structure and the archive timeline

<img width="205" alt="Screen Shot 2022-07-18 at 6 51 29 PM" src="https://user-images.githubusercontent.com/625889/179630272-fd383033-7024-4b4a-9b83-732264ca7a39.png">

That's a good question. There's no relation as of now:
- The API doesn't indicate in which folder an archive resides.
- For me this list needs to answer these two questions: Have I already created an archive for this page? If so, when was the last time I did? I think that adding folders hierarchy on top might not help with clarity. 

---

Cheers,

**Comment by shljessie** [comment]
> ### Re: "Ready" status message
> This is the default status message that shows a few seconds after any action is completed (or errored out!). I agree that it's a bit unclear, and I am not sure what to put there. Suggestions welcome 😄 .

> 
> ### Re: Archive IDs
> <img alt="Screen Shot 2022-07-18 at 6 13 48 PM" width="231" src="https://user-images.githubusercontent.com/625889/179626213-e432fe72-51ab-4cce-b852-434fdd3763ce.png">
> 
> I am not certain I 100% understand your question. Do you mean: how do IDs get assigned and why are they in this format?


> ### Re: More precise status messages when switching between private and public mode
> Agreed, this needs to be more precise. I think this works a bit better?
> 
>  Screen.Recording.2022-07-18.at.6.33.12.PM.mov 
> ### Re: Changing color of privacy toggle buttons based on current status
> That's a good idea, I think 👍 . Implemented the following.
> 
>  Screen.Recording.2022-07-18.at.6.40.47.PM.mov 
> ### Re: Relation between the user's file structure and the archive timeline
> <img alt="Screen Shot 2022-07-18 at 6 51 29 PM" width="205" src="https://user-images.githubusercontent.com/625889/179630272-fd383033-7024-4b4a-9b83-732264ca7a39.png">
> 
> That's a good question. There's no relation as of now:
> 
> * The API doesn't indicate in which folder an archive resides.
> * For me this list needs to answer these two questions: Have I already created an archive for this page? If so, when was the last time I did? I think that adding folders hierarchy on top might not help with clarity.
> 
> Cheers,

**Comment by shljessie** [comment]
Re: Archive IDs
Screen Shot 2022-07-18 at 6 13 48 PM

> I was thinking that it could be confusing since the link name is a unique archive ID instead of the link name!

**Comment by shljessie** [comment]
https://user-images.githubusercontent.com/625889/179629294-dd644b6c-bd43-404a-81e6-f599f708e1e4.mov
