### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by matteocargnelutti** [harvard-lil/perma-extension#27]

**Comment by shljessie** [comment]
@matteocargnelutti 
I think the dark mode color scheme looks great! 

I have two questions in this section! 
<img width="89" alt="Screen Shot 2022-07-26 at 10 24 05 AM" src="https://user-images.githubusercontent.com/59305253/181030541-e9799149-ed99-4f82-93a7-3a06348e30b2.png">


1. Why did the icon for the archiving change from the lock to this arrow (with files?) 
2. Wondering if we should do an accessibility check for the slight color change in the making the link public button? I think the contrast in the colors could be a little low. I would be happy to do this and suggest some colors!  https://coolors.co/contrast-checker/112a46-acc8e5

**Comment by matteocargnelutti** [comment]
@shljessie 
Thank you very much for having a look 😄 , much appreciated.

---

> Why did the icon for the archiving change from the lock to this arrow (with files?)

(Missing context discussed on Slack)

---

> Wondering if we should do an accessibility check for the slight color change in the making the link public button? I think the contrast in the colors could be a little low. I would be happy to do this and suggest some colors! https://coolors.co/contrast-checker/112a46-acc8e5

That's always a good idea 😄 . 
I did check contrast ratios as I edited the colors for the dark theme, but suggestions are more than welcome! 

For the _"white on blue"_ buttons, I get a score of `4.59` in its default state, `4.77` on `:hover`. It probably can be improved!

<img width="1047" alt="Screen Shot 2022-07-26 at 10 35 30 AM" src="https://user-images.githubusercontent.com/625889/181035848-e03b305e-3d9b-4167-a999-b6b52865d2fc.png">

<img width="1047" alt="Screen Shot 2022-07-26 at 10 36 18 AM" src="https://user-images.githubusercontent.com/625889/181035853-8ff652e5-b034-45c3-97dc-3a000b852c84.png">

You'll find the color schemes I use here:
- https://github.com/harvard-lil/perma-extension/blob/develop/src/popup/index.css#L11
- https://github.com/harvard-lil/perma-extension/blob/develop/src/popup/index.css#L34

--- 

Thanks again,

**Comment by shljessie** [comment]
Cool! I was talking more about the button background color change from a lighter blue to a darker blue when clicked! 
But if the function for the button is now a copy link instead of an archive/public, I think the current color change from a lighter blue to a darker blue is good enough to let the user know it has been clicked!

**Comment by matteocargnelutti** [comment]
@shljessie I see, cool! Thanks again for having a look 👍 !
